const portfolioData = {
    Companies: [
        {
            Title: 'Severex', TimePeriod: 'Sep 2024 - Today', Skills: ['Unity 2D', 'Web requests'],
            Games: [
                { Title: 'Arrows Unjam', Description: 'FX heavy 2d puzzle with fine-tuned movement and ASMR feel', TimePeriod: 'June 2026', Skills: ['Unity 3D'], ImageSrc: '/imgs/arrows-unjam.webp', YoutubeLink: '', PlayLink: 'https://play.google.com/store/apps/details?id=com.severex.arrows.unjam.out.puzzle', AppMagicLink: 'https://appmagic.rocks/google-play/arrows-unjam-color-sort-puzzle/com.severex.arrows.unjam.out.puzzle', RepositoryLink: '' },
                { Title: 'Mixsaw', Description: 'Jigsaw-like with unique controls', TimePeriod: 'April 2026', Skills: ['Unity 3D'], ImageSrc: '/imgs/mixsaw.webp', YoutubeLink: 'https://youtu.be/rAo9zJMtePE', PlayLink: 'https://play.google.com/store/apps/details?id=com.severex.jigsaw.picture.slide.solitaire.puzzle', AppMagicLink: 'https://appmagic.rocks/google-play/mixsaw-sliding-jigsaw-puzzle/com.severex.jigsaw.picture.slide.solitaire.puzzle', RepositoryLink: '' },
                { Title: 'Word Vie', Description: 'Fake PvP association + tic tac toe. Featuring matchmaking, advanced bots and smart shuffling', TimePeriod: 'January 2026', Skills: ['Unity 3D'], ImageSrc: '/imgs/', YoutubeLink: 'https://youtu.be/KMSxy7m5vtQ', PlayLink: 'https://play.google.com/store/apps/details?id=com.severex.word.connections.association.puzzle.connect', AppMagicLink: 'https://appmagic.rocks/google-play/word-vie-match-associations/com.severex.word.connections.association.puzzle.connect', RepositoryLink: '' },
                { Title: 'Cryptogram', Description: 'Word puzzle', TimePeriod: 'September 2025', Skills: ['Unity 3D'], ImageSrc: '/imgs/cryptogram.webp', YoutubeLink: 'https://youtu.be/sWP0GlWjyek', PlayLink: 'https://play.google.com/store/apps/details?id=com.severex.cryptogram.cross.word.puzzle.code', AppMagicLink: 'https://appmagic.rocks/google-play/cryptogram-code-word-puzzle/com.severex.cryptogram.cross.word.puzzle.code', RepositoryLink: '' },
                { Title: 'Dixie Poker', Description: 'Poker + solitaire combination. Features a customization system, allowing to change the appearance of the game in one click', TimePeriod: 'January 2025', Skills: ['Unity 3D'], ImageSrc: '/imgs/dixie-poker.jpg', YoutubeLink: 'https://youtu.be/0UGaoi8QMN0', PlayLink: 'https://play.google.com/store/apps/details?id=com.severex.poker.solitaire.classic.cards', AppMagicLink: 'https://appmagic.rocks/google-play/dixie-poker-solitaire-puzzle/com.severex.poker.solitaire.classic.cards', RepositoryLink: '' }
            ]
        },
        {
            Title: "Butcher's Games", TimePeriod: 'Jun 2024 - Aug 2024', Skills: ['Unity 3D', 'Blender', 'Shader Graph', 'Asset Ripper'],
            Games: [
                { Title: 'Archery Clash', Description: "Voodoo's game ported for Web", TimePeriod: 'July 2024', Skills: ['Unity 3D', 'Blender', 'Shader Graph', 'Asset Ripper'], ImageSrc: '/imgs/archery_clash.png', YoutubeLink: 'https://youtu.be/gdOqL7gS1Yc', PlayLink: 'https://yandex.ru/games/app/359525?draft=true', AppMagicLink: '', RepositoryLink: '' },
                { Title: 'Flick Goal', Description: "Voodoo's game ported for Web", TimePeriod: 'June 2024', Skills: ['Unity 3D', 'Blender', 'Shader Graph', 'Asset Ripper'], ImageSrc: '/imgs/flick_goal.png', YoutubeLink: 'https://youtu.be/1WJgf6X2X94', PlayLink: 'https://yandex.ru/games/app/348616?draft=true', AppMagicLink: '', RepositoryLink: '' }
            ]
        },
        {
            Title: 'Panda Play', TimePeriod: 'Jul 2021 - Oct 2023', Skills: ['Unity 3D', 'C#'],
            Games: [
                { Title: 'Zombie Bulldozer', Description: 'Player (custom bulldozer controller) is pushing hoards of zombies (navmesh) off of cliffs in realistic graphics', TimePeriod: 'Development period: 2022', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/zombie_bulldozer.png', YoutubeLink: 'https://youtu.be/dQw4w9WgXcQ', PlayLink: 'https://play.google.com/store/apps/details?id=com.me.zombiebulldozer', AppMagicLink: 'https://appmagic.rocks/google-play/buldozer-vs-zombie/com.me.zombiebulldozer', RepositoryLink: '' },
                { Title: 'Body Maze', Description: 'Joints bazed main character is navigating various levels, solving puzzles', TimePeriod: 'Development period: 2023', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/body_maze.png', YoutubeLink: 'https://youtu.be/G6lJX_mSsrU', PlayLink: 'https://play.google.com/store/apps/details?id=me.bodymaze.puzzle', AppMagicLink: 'https://appmagic.rocks/google-play/body-maze-puzzle/me.bodymaze.puzzle', RepositoryLink: '' },
                { Title: 'Pixel Slice', Description: 'Arcade, action-heavy game. Optimized to allow lots of objects and destruction. Textures are converted to levels on the fly', TimePeriod: 'Development period: 2023', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/pixel_slice.png', YoutubeLink: 'https://youtu.be/3zsxPEiyM3o', PlayLink: 'https://play.google.com/store/apps/details?id=me.pixel.slice', AppMagicLink: 'https://appmagic.rocks/google-play/pixel-slice/me.pixel.slice', RepositoryLink: '' },
                { Title: 'Eco Recycler', Description: 'Idler game with orders and production lines', TimePeriod: 'Development period: 2022', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/eco_recycler.png', YoutubeLink: 'https://youtu.be/37kEOJlkiMY', PlayLink: 'https://play.google.com/store/apps/details?id=com.pandaplay.ecorecycler', AppMagicLink: 'https://appmagic.rocks/google-play/eco-recycler/com.pandaplay.ecorecycler', RepositoryLink: '' },
                { Title: 'Soccer Strike', Description: 'Full-on soccer simulator with passes and goal hits', TimePeriod: 'Development period: 2023', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/soccer_strike.png', YoutubeLink: 'https://youtu.be/5AAjXLVJHTQ', PlayLink: 'https://play.google.com/store/apps/details?id=me.soccer.strike', AppMagicLink: 'https://appmagic.rocks/google-play/soccer-strike/me.soccer.strike', RepositoryLink: '' },
                { Title: 'Wild West', Description: 'RPG resource gathering game / idler. Hunting animals in different biomes', TimePeriod: 'Development period: 2023', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/wild_west.png', YoutubeLink: 'https://youtu.be/x45Db3IjfTs', PlayLink: 'https://play.google.com/store/apps/details?id=com.mydirectgames.wildwest', AppMagicLink: 'https://appmagic.rocks/google-play/wild-west-idle-rpg/com.mydirectgames.wildwest', RepositoryLink: '' },
                { Title: 'Bath Toy Puzzle', Description: 'Puzzle combining 3D graphics with 2D water sim', TimePeriod: 'Development period: 2022', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/bath_toy.png', YoutubeLink: 'https://youtu.be/6XjHYrIyN98', PlayLink: 'https://play.google.com/store/apps/details?id=me.bathtoy.puzzle', AppMagicLink: 'https://appmagic.rocks/google-play/toy-bath-puzzle/com.pandaplay.toybathpuzzle', RepositoryLink: '' },
                { Title: 'Jetski Racing', Description: 'Jetski racing simulator with custom controls, map track builder and enemy AI that always stays not too close and not too far away', TimePeriod: 'Development period: 2023', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/jetski_racing.png', YoutubeLink: 'https://youtu.be/rPMEL8SydqA', PlayLink: 'https://play.google.com/store/apps/details?id=me.jetski.racing', AppMagicLink: 'https://appmagic.rocks/google-play/jetski-racing/com.jetski.racing', RepositoryLink: '' },
                { Title: 'Tiny Stylist', Description: 'Idler/production line game with cool visuals', TimePeriod: 'Development period: 2023', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/tiny_stylist.png', YoutubeLink: 'https://youtu.be/9YhpfFFwTN0', PlayLink: 'https://play.google.com/store/apps/details?id=tiny.stylist', AppMagicLink: '', RepositoryLink: '' },
                { Title: 'Ragdoll Fight', Description: 'Runner/Slasher. Combining 2 rigs (ragdoll controlled and animator controlled) to create a more physical animation', TimePeriod: 'Development period: 2021', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/ragdoll_fight.png', YoutubeLink: 'https://youtu.be/UvyE3gKU_yU', PlayLink: 'https://play.google.com/store/apps/details?id=me.ragdoll.fight', AppMagicLink: 'https://appmagic.rocks/google-play/ragdoll-fighting-run/com.ragdoll.fightingrun', RepositoryLink: '' },
                { Title: 'Blockbox', Description: 'Procedurally generated world (biomes, landscape, caves, trees etc). Never was more than a prototype, but a cool experience nonetheless', TimePeriod: 'Development period: 2023', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/block_box.png', YoutubeLink: 'https://youtu.be/yc-tVbAjTXU', PlayLink: 'https://play.google.com/store/apps/details?id=me.blockbox', AppMagicLink: 'https://appmagic.rocks/google-play/block-box/com.pandaplay.blockbox', RepositoryLink: '' },
                { Title: 'GTA Arcade', Description: 'GTA inspired game. I really loved the likeness to the original and the chase mechanic with custom AI car controls', TimePeriod: 'Development period: 2023', Skills: ['Unity 3D', 'C#'], ImageSrc: '/imgs/gta_arcade.png', YoutubeLink: 'https://youtu.be/4Hxu6KUxoNA', PlayLink: '', AppMagicLink: '', RepositoryLink: '' }
            ]
        },
        {
            Title: 'My Pet Projects', TimePeriod: '', Skills: ['Unity 3D'],
            Games: [
                { Title: 'SCP 173: Foundation Escape', Description: 'Stealth-action arcade game. Smart enemies with different behaviours. Multiple characters with unique abilities', TimePeriod: '2025', Skills: ['Unity 3D', 'NavMesh', 'Mesh Generation', 'Shaders'], ImageSrc: '/imgs/scp-173.webp', YoutubeLink: '', PlayLink: 'https://play.google.com/store/apps/details?id=com.ChimericalDream.SCP173Escape', AppMagicLink: 'https://appmagic.rocks/google-play/scp-173-foundation-escape/com.ChimericalDream.SCP173Escape', RepositoryLink: '' },
                { Title: 'Drift Online', Description: 'The first online game i ever made, this is a fun drifting game inspired by Drift Streets Japan', TimePeriod: '2024', Skills: ['Unity 3D', 'Wheel Collider', 'Photon Fusion 1-2'], ImageSrc: '/imgs/drift_online.png', YoutubeLink: '', PlayLink: '', AppMagicLink: '', RepositoryLink: '' },
                { Title: 'Earthquake Escape', Description: 'Thrilling infinite runner', TimePeriod: '2021', Skills: ['Unity 3D', 'Mixamo', 'Blender 3D', 'Procedural Generation'], ImageSrc: '/imgs/earthquake_escape.png', YoutubeLink: '', PlayLink: 'https://reddycat.itch.io/earthquake-escape', AppMagicLink: '', RepositoryLink: '' }
            ]
        }
    ]
};
